dist: bionic
osx_image: xcode11.3
language: go
go:
- 1.14.x
os:
- linux
install: echo
script: docker/kopia-alpine/build.sh kanisterio/kopia
git:
  depth: 10
env:
- GO111MODULE=on
import: docker/travis.yml
